### ISSUE TITLE
do I need to buy some tokens 

### ISSUE THREAD

**Issue by KeparYTbcc** [avocardio/GPT-agents#1]
on my openai api key, do I need to buy tokens?

or its 100% Free

**Comment by avocardio** [comment]
Hi, you have to have an OpenAI API key. I think you get some free credit at the beginning, but then have to pay afterwards. Here is a short guide for that: https://elephas.app/blog/how-to-create-openai-api-keys-cl5c4f21d281431po7k8fgyol0
